---
layout:     post
author:     bcnote3314
title: 	go 언어 - 7
subtitle: ㄱㄱㄱ
category: Note
tags: 		go
---

# 함수

## 기본 사용 방법

이미 main 함수를 써봤다.  
다른 언어의 함수와 사용 방식은 동일하다.  

다만 Go언어의 함수의 경우 정의할떄 위치의 제약이 없다.  
(C/C++ 에서는 함수의 선언이나 정의(프로토 타입)이 호출부 보다 상단에 있어야만 한다.)  

기본적으로 함수를 정의하는 방법은 다음과 같다.

```
func 함수명(매개변수명 자료형, 매개변수명 자료형, [필요한 만큼]) 리턴값자료형 {} 
```

특이한점은 리턴값에 이름을 지정할 수도 있다는 점이다.

```go

func sum(a int, b int) (result int) {
	result = a + b
	reutrn
}

```

이때 이미 result라는 리턴 변수에 값을 넣었기 때문에 return뒤에 별다른 변수명을 지정하지 않는다.  

또한 return 값을 여러개 사용할 수도 있다.  

```go

func arithmeticOperation(a int, b int) (sum int, diff int, mul int, div int) {
	sum = a + b
	diff = a - b
	mul = a * b
	div = a / b
	
	return
}
```

## 가변인자 

Go언어는 가변인자도 지원한다.  
가변인자는 매개변수의 개수가 정해지지 않고 동적으로 변하는 형태를 말한다.  
Go에서는 가변인자를 슬라이스 타입으로 처리한다.  
매개변수를 전달할때 슬라이스의 형태로 주어도 되고, 여러개의 변수를 입력해도된다.  

```go

func main() {
        slice := []int{1,2,3}
        result1 := sum(slice...) //slice는 레퍼런스 타입이기 때문에 모든 인자를 넘겨주기 위하여 ...를 붙인다.
        result2 := sum(1,2,3)
        fmt.Println(result1, result2)
}

func sum(n ...int) int {
        sumValue := 0
        for _, value := range(n) {
                sumValue += value
        }
        return sumValue
}

```

## 변수에 저장하기

Go는 변수에 함수를 저장할 수 있다.  
단순한 변수 뿐아니라 슬라이스나 맵의 요소로도 사용이 가능하다.  

```

func sum(a int, b int) int {
	return a + b
}

func diff(a int, b int) int {
	return a - b
}

func main() {
	// 변수에 대입
	var fun1 func(a int, b int) int = sum
	fun2 :=  diff
	
	fmt.Println(fun1(1, 2))
	fmt.Println(fun2(1, 2))
	
	//슬라이스 요소에 대입
	fun3 := []func(int, int) int{sum, diff}
	
	fmt.Println(fun3[0](1, 2))
	fmt.Println(fun3[1](1, 2))
	
	//맵 요소에 대입
	fun4 := map[string]func(int, int) int{"sum":sum, "diff":diff}
	
	fmt.Println(fun4["sum"](1, 2))
	fmt.Println(fun4["diff"](1, 2))
}

```

## 익명 함수

Go는 Javascript와 같은 익명함수를 정의한뒤 바로 호출할 수 있다.  

```go

func main () {
	func() {
		fmt.Println("Hello")
	}()
	
	fumc(str string) {
		fmt.Println(str)
	}("Hello")
	
	str := func() string {
		return "Hello"
	}()
}

```

익명함수는 코드의 양을 줄이는데 도움을 주며 클로저, 지연호출, 고루틴에서 사용되는 문법이기 때문에 추후 다시 다룬다. 

# 클로저 (아직 이해가 잘 안감..)

클로저는 함수안에서 함수를 선언할 수 있고, 바깥 삼수에 선언된 변수에도 접근이 가능한 함수를 말한다.  

안쪽 함수(클로저)는 바깥함수의 변수로 관리되며 바깥 변수에 접근이 가능하다.  

```go
func main () {
	a,b := 1, 2
	
	fun := func (c int) int {
		return a + b + c
	}
	
	result := fun(3)
	
	fmt.Println(result) // 6
}
```

클로저는 언제 사용될까?  
지역변수는 함수 실행이 끝나는 순간 소멸한다.  
하지만 클로저를 사용하면?  

```go

package main

import "fmt"

func nextValue() func() int { //리턴 자료형으로 함수도 가능하다.
	i := 0
	return func () int {
		i++
		return i
	}
}

func main () {
	next := nextValue()
	
	fmt.Println(next()) //1
	fmt.Println(next()) //2
	fmt.Println(next()) //3
	
	next2 := nextValue()
	
	fmt.Println(next()) //1
	fmt.Println(next()) //2
	fmt.Println(next()) //3	
}

```

위 예제에서 nextValue 함수는 클로저로 사용되는 익명함수를 return 한다.  
클로저를 사용하면 지역변수가 소멸하지 않고 사용이 가능하다.  
이런 클로저는 함수형 언어의 특징이라고 할수 있기 때문에 반드시 이해가 필요하다.  

(나중에 메모리 구조상 어떻게 동작하는지도 한번 찾아봐야 할것같다.)

또한 클로저를 사용할때 보통 익명함수를 사용한다.  
하지만 익명함수 != 클로저 이기 때문에 둘간의 차이점을 명확히 이해해야 한다.  

# 지연 호출

지연 호출은 특정 함수를 혀재 함수가 끝나기 직전에 실행하는 기능이다.  

``` 
defer 함수명(매개변수)
```

지연 호출한 함수가 실행되는 순서는 자료구조의 스택과 동일하다. 가장 마지막에 지연호출을 한 함수가 그중 제일 먼저 호출된다.  

지연 호출을 자주 사용하는 곳은 파일 입출력 등과 같이 후처리가 필요한 것들이다.
open 이후 close를 지연 호출로 처리하면 함수가 끝날때 항상 파일을 닫고 종료하게 된다.  
즉 C/C++에서 에러 처리로 인하여 분기가 복잡해지는 경우 아주 유용하게 사용될 수 있다.  

# 패닉 / 복구

프로그램 동작중 에러로 인하여 종료되는 상황이 패닉이다. (runtime error)  
실제 동작과정에서 발생하는 에러는 아니지만 논리적인 로직에 따라 에러로 처리하고 싶을 떄 panic 을 통해 강제로 에러를 발생시킬 수 있다.  

```go

package main

import "fmt"


func main() {
        panic("Error")
        fmt.Println("Hello")
}


$ go run panic.go
panic: Error
```

recover는 패닉이 발생했을 떄 프로그램이 종료되지 않고 예외처리를 할수 있다.  
다른 언어의 try와 비슷한 개념이다.  

```go
package main

import "fmt"


func panicFunc() {
        defer func () {
                s := recover()
                fmt.Println(s)
        }()

        arr := [...]int{1,2,3,4,5}
        idx := 5
        arr[idx] = 6
}

func main() {
        panicFunc()

        fmt.Println("End Main")

}

$ go run panic.go
runtime error: index out of range
End Main

```

일단 recover 함수는 반드시 defer를 통해 지연 호출해야한다.  
특정 함수 내에서 runtime error가 발생한 경우 바로 함수가 종료되는데 이때 지연함수가 호출되면서 recover가 동작하는 형태이다.  

즉 해당 함수의 실행은 에러가 발생한 시점에서 끝이며 바로 지연함수가 실행된다.  
하다보니 재밌는건 지연함수를 여러개 호출하더라도 모든 지연함수가 처리된다는 점이다.  

runtime error -> 함수 종료전 지연함수 호출 -> 그중에recover가 있었다면 함수 호출 이후 내용 수행 -> 아니면 error로 종료 되는 형태다.  

